version: '3'
services:
  bkchat-fe:
    build:
      context: .
      args:
        REACT_APP_SERVER_ADDRESS: ${REACT_APP_SERVER_ADDRESS}
    container_name: bkchat-fe
    # restart: always
    # ports:
    #   - 3000:80

networks:
  default:
    name: bkchat
    external: true
