version: '3'
services:
  bkchat-fe:
    build: .
    container_name: bkchat-fe
    restart: always
    environment:
      REACT_APP_SERVER_ADDRESS: ${REACT_APP_SERVER_ADDRESS}
    # ports:
    #   - 3000:80

networks:
  default:
    name: bkchat
    external: true
