version: '3'
services:
  bk-chat-fe:
    container_name: bk-chat-fe
    build: .
    restart: always
    environment:
      REACT_APP_SERVER_ADDRESS: ${REACT_APP_SERVER_ADDRESS}
    # ports:
    #   - 3000:80

networks:
  default:
    name: bk-chat
    external: true
