version: "3"

services:
  imgproxy:
    image: darthsim/imgproxy:latest
    environment:
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_TTL: "604800"
    container_name: imgproxy
    # ports:
    #   - "8080:8080"

  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cache:/data/cache
      - ./proxy_params:/etc/nginx/proxy_params
