version: "3"
services:
  imgproxy:
    image: darthsim/imgproxy:latest
    environment:
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_TTL: "604800"
    container_name: imgproxy
    # ports:
    #   - "8080:8080"

networks:
  default:
    name: bkchat
    external: true
