version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    # restart: always
    ports:
      - 80:80
    # network_mode: "host"
    volumes:
      # - ./cache:/data/cache
      # - ./proxy_params:/etc/nginx/proxy_params
      # - ./imgproxy.conf:/etc/nginx/conf.d/imgproxy.conf
      - ./fe.conf:/etc/nginx/conf.d/fe.conf
      - ./node.conf:/etc/nginx/conf.d/node.conf
      # - ./portainer.conf:/etc/nginx/conf.d/portainer.conf
      # - ./grafana.conf:/etc/nginx/conf.d/grafana.conf
networks:
  default:
    name: bkchat
    external: true
