// Cron job for add chats
pipeline {
    agent any
    // triggers {
    //   cron '*/5 * * * *'
    // }
    // BUILD_NUMBER
    tools { nodejs "NodeJS" }
    environment {
        PROJECT = "BK-Chat"
        MONGODB_SERVER = "mongodb://admin:admin12345@mongodb:27017/BK-Chat?authSource=admin"
        STEP = "1"
        NUMBER = "20"
        HOURS = "8"
        MAX_HOURS = "3"
    }
    stages {
        stage('Generate data') {
            steps {
                sh '''
                    cd ..
                    cd ${PROJECT}/nlp/src/functions/add-chats/
                    echo "MONGODB_SERVER=${MONGODB_SERVER}\nSTEP=${STEP}\nNUMBER=${NUMBER}\nHOURS=${HOURS}\nMAX_HOURS=${MAX_HOURS}" > .env
                    node index.js
                '''
            }
        }
    }
}
