pipeline {
    agent any
    // triggers {
    //   cron '*/5 * * * *'
    // }
    environment {
        PROJECT = "BK-Chat"
        MONGODB_SERVER = "mongodb://admin:admin12345@mongodb:27017/BK-Chat?authSource=admin"
        NUMBER = "100"
    }
    stages {
        stage('Gen data') {
            steps {
                sh '''
                    cd ..
                    cd ${PROJECT}/nlp/src/functions/add-chats/
                    echo "MONGODB_SERVER=${MONGODB_SERVER}\nSTEP=${BUILD_NUMBER}\nNUMBER=${NUMBER}" > .env
                '''
            }
        }
    }
}
