# Set up mongo db server with docker compose
version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
  neo4j:
    container_name: neo4j
    image: neo4j:community
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
volumes:
  mongo_data:
    external: true
  redis_data:
    external: true
  neo4j_data:
    external: true
networks:
  default:
    name: bk-chat
    external: true
